# -*- coding: utf-8 -*-
"""installation_and_QC

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tE0171HGQnNJZnjs5ja0HDDd8v3KeEka

#GigaTIME intallations
"""

# Clone GigaTIME repo and install dependencies #9
!git clone https://github.com/prov-gigatime/GigaTIME /content/GigaTIME 2>/dev/null || echo "already cloned"

import sys
sys.path.insert(0, '/content/GigaTIME/scripts')  # archs.py lives in scripts/, not repo root

# environment.yml is a conda file — install key deps directly with pip
!pip install -q albumentations scikit-learn scipy easydict tqdm

import torch
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(f"Device: {device}")

# Download GigaTIME model weights from Hugging Face #10
from huggingface_hub import snapshot_download
from google.colab import userdata
import os

HF_TOKEN = userdata.get('HF_TOKEN')

MODEL_DIR = f'{DRIVE_BASE}/gigatime_model'
os.makedirs(MODEL_DIR, exist_ok=True)

snapshot_download(
    repo_id="prov-gigatime/GigaTIME",
    local_dir=MODEL_DIR,
    token=HF_TOKEN,
    ignore_patterns=["*.md", "*.txt"]
)

print("Files downloaded:")
for f in os.listdir(MODEL_DIR):
    size = os.path.getsize(os.path.join(MODEL_DIR, f)) / 1e6
    print(f"  {f}  ({size:.1f} MB)")

# Load GigaTIME via official archs.py (prov-gigatime/GigaTIME)
import torch, sys, os
sys.path.insert(0, '/content/GigaTIME/scripts')
import archs

device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(f"Device: {device}")

# 23 output channels: 21 protein markers + TRITC + Cy5 (background channels)
model = archs.gigatime(num_classes=23, input_channels=3).to(device)
state_dict = torch.load(f'{MODEL_DIR}/model.pth', map_location=device)
model.load_state_dict(state_dict)
model.eval()

n_params = sum(p.numel() for p in model.parameters())
print(f"✓ GigaTIME loaded  |  {n_params:,} parameters")

# Sanity-check: model expects 256×256 windows
dummy_win = torch.randn(1, 3, 256, 256).to(device)
with torch.no_grad():
    out = model(dummy_win)
print(f"  Window input : {dummy_win.shape}")
print(f"  Window output: {out.shape}  ← expected [1, 23, 256, 256]")

import matplotlib.pyplot as plt #12
import random

sample_indices = random.sample(range(len(patches)), min(12, len(patches)))
sample_patches = [patches[i] for i in sample_indices]

fig, axes = plt.subplots(2, 6, figsize=(14, 5))
for i, ax in enumerate(axes.flat):
    if i < len(sample_patches):
        ax.imshow(sample_patches[i])
    else:
        ax.imshow(np.ones((256,256,3), dtype=np.uint8)*255)
    ax.axis('off')

plt.suptitle(f'Sample tissue patches — {patient_id}  ({len(patches)} total)')
plt.tight_layout()
plt.savefig(f'{RESULTS_DIR}/patches_full_{patient_id}.png', dpi=80)
plt.show()

"""# Check the Slides and available pixel data"""

# Quick check — how big is this slide really? #13
from wsidicom import WsiDicom

patient_id, test_dir = series_list[0]
wsi = WsiDicom.open(test_dir)
w = wsi.levels.base_level.size.width
h = wsi.levels.base_level.size.height
wsi.close()

patch_size = 256
total_positions = ((h - patch_size) // patch_size) * ((w - patch_size) // patch_size)
print(f"Slide size     : {w} x {h} px")
print(f"Total positions: {total_positions}")
print(f"Tissue patches : {len(patches)}  (after tissue threshold filtering)")
print(f"Coverage       : {len(patches)/total_positions*100:.1f}% of slide is tissue")

# Check what threshold 220 is catching #14
import numpy as np
import matplotlib.pyplot as plt

# Sample 200 random patches and plot their mean pixel values
sample_means = []
from wsidicom import WsiDicom

wsi = WsiDicom.open(test_dir)
patch_size = 256
count = 0
for y in range(0, 5000, patch_size):
    for x in range(0, 5000, patch_size):
        try:
            region = wsi.read_region((x, y), 0, (patch_size, patch_size))
            arr = np.array(region.convert('RGB'))
            sample_means.append(arr.mean())
            count += 1
            if count >= 200:
                break
        except:
            continue
    if count >= 200:
        break
wsi.close()

plt.figure(figsize=(10, 4))
plt.hist(sample_means, bins=50, color='steelblue', edgecolor='black')
plt.axvline(x=220, color='red', linestyle='--', linewidth=2, label='threshold=220')
plt.xlabel('Mean pixel value')
plt.ylabel('Count')
plt.title('Patch mean pixel distribution — red line = tissue threshold')
plt.legend()
plt.tight_layout()
plt.show()

tissue = sum(1 for m in sample_means if m < 220)
print(f"Below threshold (tissue): {tissue}/200 = {tissue/2:.0f}%")
print(f"Above threshold (background): {200-tissue}/200 = {(200-tissue)/2:.0f}%")

# Better check — sample from across the whole slide randomly #15
import numpy as np
import matplotlib.pyplot as plt
from wsidicom import WsiDicom
import random

wsi = WsiDicom.open(test_dir)
w = wsi.levels.base_level.size.width
h = wsi.levels.base_level.size.height
patch_size = 256

# Generate all possible positions
all_positions = [
    (x, y)
    for y in range(0, h - patch_size, patch_size)
    for x in range(0, w - patch_size, patch_size)
]

# Sample 500 random positions from across whole slide
sampled = random.sample(all_positions, min(500, len(all_positions)))

sample_means = []
for x, y in sampled:
    try:
        region = wsi.read_region((x, y), 0, (patch_size, patch_size))
        arr = np.array(region.convert('RGB'))
        sample_means.append(arr.mean())
    except:
        continue
wsi.close()

plt.figure(figsize=(10, 4))
plt.hist(sample_means, bins=50, color='steelblue', edgecolor='black')
plt.axvline(x=220, color='red', linestyle='--', linewidth=2, label='threshold=220')
plt.xlabel('Mean pixel value')
plt.ylabel('Count')
plt.title('Patch mean pixel distribution — whole slide random sample')
plt.legend()
plt.tight_layout()
plt.show()

tissue = sum(1 for m in sample_means if m < 220)
background = len(sample_means) - tissue
print(f"Tissue patches   (< 220): {tissue}/{len(sample_means)} = {tissue/len(sample_means)*100:.1f}%")
print(f"Background patches(≥220): {background}/{len(sample_means)} = {background/len(sample_means)*100:.1f}%")
print(f"\nIf ~17-20% tissue → threshold is correct, proceed to Cell 19")
print(f"If tissue cluster exists below 200 → threshold fine")
print(f"If tissue cluster sits between 200-220 → might need to raise threshold slightly")

# Fast slide QC
import os
import pandas as pd
import matplotlib.pyplot as plt
from collections import defaultdict

# Group by patient, find largest series (highest resolution)
patient_series_map = defaultdict(list)
for pid, sdir in series_list:
    dcm_files = [f for f in os.listdir(sdir) if f.endswith('.dcm')]
    total_size_mb = sum(
        os.path.getsize(os.path.join(sdir, f))
        for f in dcm_files
    ) / 1e6
    n_files = len(dcm_files)
    patient_series_map[pid].append({
        'sdir': sdir,
        'size_mb': total_size_mb,
        'n_files': n_files
    })

# For each patient, pick the largest series
slide_stats = []
for pid, series in patient_series_map.items():
    best = max(series, key=lambda x: x['size_mb'])
    slide_stats.append({
        'PatientID' : pid,
        'best_sdir' : best['sdir'],
        'size_mb'   : round(best['size_mb'], 1),
        'n_dcm_files': best['n_files'],
        'n_series'  : len(series)
    })

stats_df = pd.DataFrame(slide_stats).sort_values('size_mb', ascending=False)
stats_df.to_csv(f'{SCORES_DIR}/slide_file_stats.csv', index=False)

print(f"Unique patients : {len(stats_df)}")
print(f"Total series    : {len(series_list)}")
print(f"\n=== Slide size distribution ===")
print(stats_df['size_mb'].describe().round(1))

print(f"\n=== Smallest slides (potential problem slides) ===")
print(stats_df[['PatientID','size_mb','n_dcm_files','n_series']].tail(10).to_string(index=False))

print(f"\n=== Largest slides ===")
print(stats_df[['PatientID','size_mb','n_dcm_files','n_series']].head(10).to_string(index=False))

# Plot
fig, axes = plt.subplots(1, 2, figsize=(14, 4))

axes[0].hist(stats_df['size_mb'], bins=30, color='steelblue', edgecolor='black')
axes[0].set_xlabel('Slide size (MB)')
axes[0].set_ylabel('Count')
axes[0].set_title('Slide size distribution across all patients')
axes[0].axvline(stats_df['size_mb'].median(), color='red',
                linestyle='--', label=f"median={stats_df['size_mb'].median():.0f} MB")
axes[0].legend()

axes[1].hist(stats_df['n_series'], bins=20, color='coral', edgecolor='black')
axes[1].set_xlabel('Number of DICOM series per patient')
axes[1].set_ylabel('Count')
axes[1].set_title('Series count per patient')

plt.tight_layout()
plt.savefig(f'{RESULTS_DIR}/slide_file_stats.png', dpi=100)
plt.show()

# Visually check the 6 smallest slides + our test patient #17
import matplotlib.pyplot as plt
from wsidicom import WsiDicom
import logging
logging.getLogger('wsidicom').setLevel(logging.ERROR)

# Patients to spot-check
check_patients = (
    stats_df.nsmallest(6, 'size_mb')['PatientID'].tolist() +   # 6 smallest
    stats_df.nlargest(3,  'size_mb')['PatientID'].tolist() +   # 3 largest
    ['C3N-03211']                                               # our test patient
)

fig, axes = plt.subplots(2, 5, figsize=(20, 8))

for ax, pid in zip(axes.flat, check_patients):
    # Get best series dir for this patient
    row = stats_df[stats_df['PatientID'] == pid].iloc[0]
    sdir = row['best_sdir']
    size = row['size_mb']
    try:
        wsi = WsiDicom.open(sdir)
        thumb = wsi.read_thumbnail(size=(300, 300))
        wsi.close()
        ax.imshow(thumb)
        ax.set_title(f'{pid}\n{size:.0f} MB', fontsize=8)
    except Exception as e:
        ax.set_facecolor('lightcoral')
        ax.text(0.5, 0.5, f'{pid}\nERROR\n{size:.0f} MB',
                ha='center', va='center', transform=ax.transAxes, fontsize=7)
    ax.axis('off')

# Hide unused axes
for ax in axes.flat[len(check_patients):]:
    ax.axis('off')

plt.suptitle('Slide thumbnails — small vs large vs test patient', fontsize=12)
plt.tight_layout()
plt.savefig(f'{RESULTS_DIR}/slide_thumbnails_qc.png', dpi=100)
plt.show()

# Full dataset census — thumbnail grid + per-slide stats #18
import matplotlib.pyplot as plt
from wsidicom import WsiDicom
import logging, os
import numpy as np
import pandas as pd
from tqdm.notebook import tqdm

logging.getLogger('wsidicom').setLevel(logging.ERROR)

# Ensure SCORES_DIR is defined (if it's not global already)
if 'SCORES_DIR' not in globals():
    DRIVE_BASE = '/content/drive/MyDrive/cptac_gigatime'
    SCORES_DIR = f'{DRIVE_BASE}/scores'

# Load stats_df from CSV if not already defined (e.g., after kernel restart)
if 'stats_df' not in globals():
    try:
        stats_df = pd.read_csv(f'{SCORES_DIR}/slide_file_stats.csv')
    except FileNotFoundError:
        print("Error: 'slide_file_stats.csv' not found. Please run Cell 16 to generate it.")
        # Exit or handle the error appropriately, perhaps raise it again
        raise # Re-raise if file is genuinely missing to prevent further errors

# ── 1. Generate thumbnails for ALL 168 patients ─────────────────────────────
n_patients = len(stats_df)
n_cols = 12
n_rows = (n_patients + n_cols - 1) // n_cols

fig, axes = plt.subplots(n_rows, n_cols, figsize=(n_cols * 2.5, n_rows * 2.5))
axes = axes.flat

census = []

for ax, (_, row) in zip(axes, stats_df.iterrows()):
    pid  = row['PatientID']
    sdir = row['best_sdir']
    size = row['size_mb']

    try:
        wsi   = WsiDicom.open(sdir)
        thumb = wsi.read_thumbnail(size=(200, 200))
        thumb_arr = np.array(thumb)
        w     = wsi.levels.base_level.size.width
        h     = wsi.levels.base_level.size.height
        wsi.close()

        # Quick tissue metrics from thumbnail
        gray        = thumb_arr.mean(axis=2)
        tissue_frac = (gray < 220).mean()
        n_fragments = 1  # placeholder — we'll eyeball from image

        ax.imshow(thumb)
        ax.set_title(f'{pid}\n{size:.0f}MB {tissue_frac*100:.0f}%',
                     fontsize=5, pad=1)

        census.append({
            'PatientID'    : pid,
            'size_mb'      : size,
            'slide_w'      : w,
            'slide_h'      : h,
            'thumb_tissue%': round(tissue_frac * 100, 1),
        })

    except Exception as e:
        ax.set_facecolor('#ffcccc')
        ax.text(0.5, 0.5, f'{pid}\nERROR', ha='center', va='center',
                transform=ax.transAxes, fontsize=5)
        census.append({'PatientID': pid, 'size_mb': size,
                       'thumb_tissue%': None})
    ax.axis('off')

# Hide unused axes
for ax in axes:
    ax.axis('off')

plt.suptitle(f'GigaTIME CPTAC-PDA Dataset Census — {n_patients} patients',
             fontsize=14, y=1.01)
plt.tight_layout()
plt.savefig(f'{RESULTS_DIR}/dataset_census_all_patients.png', dpi=120,
            bbox_inches='tight')
plt.show()
print(f"Saved to {RESULTS_DIR}/dataset_census_all_patients.png")

# ── 2. Save census CSV ───────────────────────────────────────────────────────
census_df = pd.DataFrame(census)
census_df.to_csv(f'{SCORES_DIR}/dataset_census.csv', index=False)

print(f"\n=== Dataset Census Summary ===")
print(f"Total patients          : {len(census_df)}")
print(f"Median slide size       : {census_df['size_mb'].median():.0f} MB")
print(f"Median thumbnail tissue : {census_df['thumb_tissue%'].median():.1f}%")
print(f"\nTissue % distribution:")
print(census_df['thumb_tissue%'].describe().round(1))

# Flag low tissue slides
low_tissue = census_df[census_df['thumb_tissue%'] < 5]
print(f"\nLow tissue slides (<5% in thumbnail): {len(low_tissue)}")
print(low_tissue[['PatientID', 'size_mb', 'thumb_tissue%']].to_string(index=False))

# Full dataset metrics
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from wsidicom import WsiDicom
from tqdm.notebook import tqdm
import logging, random

logging.getLogger('wsidicom').setLevel(logging.ERROR)

patch_size = 256
n_sample   = 200  # patches sampled per slide for stats

census = []

for _, row in tqdm(stats_df.iterrows(), total=len(stats_df), desc="Analyzing slides"):
    pid  = row['PatientID']
    sdir = row['best_sdir']
    size = row['size_mb']

    try:
        wsi = WsiDicom.open(sdir)
        w   = wsi.levels.base_level.size.width
        h   = wsi.levels.base_level.size.height

        all_pos = [
            (x, y)
            for y in range(0, h - patch_size, patch_size)
            for x in range(0, w - patch_size, patch_size)
        ]
        total_pos = len(all_pos)
        sampled   = random.sample(all_pos, min(n_sample, len(all_pos)))

        patch_means = []
        patch_stds  = []
        patch_r     = []   # red channel mean
        patch_g     = []   # green channel mean
        patch_b     = []   # blue channel mean

        for x, y in sampled:
            try:
                region = wsi.read_region((x, y), 0, (patch_size, patch_size))
                arr    = np.array(region.convert('RGB'))
                patch_means.append(arr.mean())
                patch_stds.append(arr.std())
                patch_r.append(arr[:,:,0].mean())
                patch_g.append(arr[:,:,1].mean())
                patch_b.append(arr[:,:,2].mean())
            except:
                continue
        wsi.close()

        patch_means = np.array(patch_means)
        patch_stds  = np.array(patch_stds)

        tissue_mask = patch_means < 220

        census.append({
            'PatientID'           : pid,
            'size_mb'             : size,
            'slide_w'             : w,
            'slide_h'             : h,
            'total_positions'     : total_pos,
            # Tissue coverage
            'tissue_frac'         : tissue_mask.mean().round(3),
            'est_tissue_patches'  : int(tissue_mask.mean() * total_pos),
            # Pixel intensity stats (all patches)
            'mean_pixel_all'      : patch_means.mean().round(1),
            'std_pixel_all'       : patch_means.std().round(1),
            # Tissue patches only
            'mean_pixel_tissue'   : patch_means[tissue_mask].mean().round(1) if tissue_mask.any() else None,
            'std_pixel_tissue'    : patch_stds[tissue_mask].mean().round(1)  if tissue_mask.any() else None,
            # Colour channels (tissue only) — H&E stain quality check
            'mean_R_tissue'       : np.array(patch_r)[tissue_mask].mean().round(1) if tissue_mask.any() else None,
            'mean_G_tissue'       : np.array(patch_g)[tissue_mask].mean().round(1) if tissue_mask.any() else None,
            'mean_B_tissue'       : np.array(patch_b)[tissue_mask].mean().round(1) if tissue_mask.any() else None,
            # Texture (high std = rich tissue, low std = fat/necrosis)
            'pct_high_texture'    : (patch_stds[tissue_mask] > 30).mean().round(3) if tissue_mask.any() else None,
        })

    except Exception as e:
        print(f"  ERROR {pid}: {e}")
        census.append({'PatientID': pid, 'size_mb': size})

census_df = pd.DataFrame(census)
census_df.to_csv(f'{SCORES_DIR}/dataset_census_full.csv', index=False)
print(f"✓ Census complete — {len(census_df)} patients")
print(census_df.describe().round(2))

# ── Plot all metrics ───────────────────────────────────────────────────────── #20
fig, axes = plt.subplots(3, 3, figsize=(18, 14))

metrics = [
    ('tissue_frac',        'Tissue coverage fraction',    'steelblue',  None),
    ('est_tissue_patches', 'Estimated tissue patches',    'teal',       None),
    ('size_mb',            'Slide size (MB)',              'slateblue',  None),
    ('mean_pixel_tissue',  'Mean pixel (tissue only)',     'coral',      None),
    ('std_pixel_tissue',   'Mean texture std (tissue)',    'darkorange', None),
    ('pct_high_texture',   'High-texture fraction (σ>30)','green',      None),
    ('mean_R_tissue',      'Mean Red channel (tissue)',    'red',        None),
    ('mean_G_tissue',      'Mean Green channel (tissue)',  'limegreen',  None),
    ('mean_B_tissue',      'Mean Blue channel (tissue)',   'royalblue',  None),
]

for ax, (col, title, color, _) in zip(axes.flat, metrics):
    data = census_df[col].dropna()
    ax.hist(data, bins=25, color=color, edgecolor='black', alpha=0.85)
    ax.axvline(data.median(), color='black', linestyle='--', linewidth=1.5,
               label=f'median={data.median():.2f}')
    # Flag outliers beyond 2 std
    lo = data.mean() - 2*data.std()
    hi = data.mean() + 2*data.std()
    n_outliers = ((data < lo) | (data > hi)).sum()
    ax.set_title(f'{title}\n(outliers >2σ: {n_outliers})', fontsize=9)
    ax.set_ylabel('Count')
    ax.legend(fontsize=8)

plt.suptitle('CPTAC-PDA Dataset Census — Slide Quality Metrics (n=168)',
             fontsize=13, y=1.01)
plt.tight_layout()
plt.savefig(f'{RESULTS_DIR}/dataset_census_metrics.png', dpi=120,
            bbox_inches='tight')
plt.show()

# ── Flag bad slides ──────────────────────────────────────────────────────────
print("\n=== Flagged slides (any metric > 2σ from mean) ===")
flag_cols = ['tissue_frac', 'mean_pixel_tissue',
             'std_pixel_tissue', 'pct_high_texture']
flagged = set()
for col in flag_cols:
    data = census_df[col].dropna()
    lo   = data.mean() - 2*data.std()
    hi   = data.mean() + 2*data.std()
    bad  = census_df[(census_df[col] < lo) | (census_df[col] > hi)]['PatientID']
    for pid in bad:
        flagged.add(pid)
    print(f"  {col:<25}: {len(bad)} flagged")

print(f"\nTotal unique flagged patients: {len(flagged)}")
print(sorted(flagged))
census_df[census_df['PatientID'].isin(flagged)][
    ['PatientID','size_mb','tissue_frac','est_tissue_patches',
     'std_pixel_tissue','pct_high_texture']
].sort_values('tissue_frac').to_string(index=False)

# Classify each patient into: GOOD / WARN / BAD / ERROR #21
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

def classify_slide(row):
    if pd.isna(row.get('tissue_frac')):
        return 'ERROR'   # wsidicom failed
    if row['tissue_frac'] < 0.03:
        return 'BAD'     # barely any tissue
    if row['pct_high_texture'] < 0.5:
        return 'BAD'     # mostly flat/artifact patches
    if row['tissue_frac'] < 0.07 or row['pct_high_texture'] < 0.7:
        return 'WARN'    # low but usable
    return 'GOOD'

census_df['status'] = census_df.apply(classify_slide, axis=1)

# Print summary
print("=== Slide Classification ===")
print(census_df['status'].value_counts().to_string())

print("\n=== BAD slides (exclude from analysis) ===")
bad = census_df[census_df['status'] == 'BAD']
print(bad[['PatientID','size_mb','tissue_frac',
           'est_tissue_patches','pct_high_texture']].to_string(index=False))

print("\n=== ERROR slides (wsidicom failed — need fixing) ===")
err = census_df[census_df['status'] == 'ERROR']
print(err[['PatientID','size_mb']].to_string(index=False))

print("\n=== WARN slides (include but flag in results) ===")
warn = census_df[census_df['status'] == 'WARN']
print(warn[['PatientID','size_mb','tissue_frac',
            'est_tissue_patches','pct_high_texture']].to_string(index=False))

# Save classified census
census_df.to_csv(f'{SCORES_DIR}/dataset_census_classified.csv', index=False)

# ── Plot: status breakdown ───────────────────────────────────────────────────
fig, axes = plt.subplots(1, 3, figsize=(16, 5))

colors = {'GOOD':'steelblue','WARN':'orange','BAD':'red','ERROR':'gray'}

# 1. Pie chart
counts = census_df['status'].value_counts()
axes[0].pie(counts, labels=counts.index,
            colors=[colors[s] for s in counts.index],
            autopct='%1.0f%%', startangle=90)
axes[0].set_title('Slide status breakdown')

# 2. Tissue fraction by status
for status, grp in census_df.groupby('status'):
    grp['tissue_frac'].dropna().plot.hist(
        ax=axes[1], alpha=0.6, bins=20,
        label=status, color=colors[status])
axes[1].set_xlabel('Tissue fraction')
axes[1].set_ylabel('Count')
axes[1].set_title('Tissue coverage by status')
axes[1].legend()

# 3. Est patches by status
for status, grp in census_df.groupby('status'):
    grp['est_tissue_patches'].dropna().plot.hist(
        ax=axes[2], alpha=0.6, bins=20,
        label=status, color=colors[status])
axes[2].set_xlabel('Estimated tissue patches')
axes[2].set_ylabel('Count')
axes[2].set_title('Patch count by status')
axes[2].legend()

plt.suptitle('CPTAC-PDA Slide Quality Classification', fontsize=13)
plt.tight_layout()
plt.savefig(f'{RESULTS_DIR}/slide_classification.png', dpi=120)
plt.show()

# ── Final recommendation ─────────────────────────────────────────────────────
good_patients  = census_df[census_df['status'] == 'GOOD']['PatientID'].tolist()
warn_patients  = census_df[census_df['status'] == 'WARN']['PatientID'].tolist()
bad_patients   = census_df[census_df['status'] == 'BAD']['PatientID'].tolist()
error_patients = census_df[census_df['status'] == 'ERROR']['PatientID'].tolist()

# Fix ERROR patients
import logging
from wsidicom import WsiDicom
from tqdm.notebook import tqdm

logging.getLogger('wsidicom').setLevel(logging.ERROR)

# Build full series map
from collections import defaultdict
patient_all_series = defaultdict(list)
for pid, sdir in series_list:
    patient_all_series[pid].append(sdir)

fixed_series = {}   # pid → working sdir

for pid in tqdm(error_patients, desc="Fixing ERROR patients"):
    for sdir in sorted(patient_all_series[pid],
                       key=lambda s: sum(
                           os.path.getsize(os.path.join(s, f))
                           for f in os.listdir(s) if f.endswith('.dcm')
                       ), reverse=True):   # try largest first
        try:
            wsi   = WsiDicom.open(sdir)
            w     = wsi.levels.base_level.size.width
            h     = wsi.levels.base_level.size.height
            # Must be a real WSI — not a thumbnail (thumbnails are tiny)
            if w > 5000 and h > 5000:
                thumb = wsi.read_thumbnail(size=(100, 100))
                wsi.close()
                fixed_series[pid] = sdir
                print(f"  ✓ {pid}: fixed → {w}x{h}")
                break
            wsi.close()
        except:
            continue
    if pid not in fixed_series:
        print(f"  ✗ {pid}: no working series found — will skip")

# Visual check of all 24 fixed ERROR patients #23
import matplotlib.pyplot as plt
from wsidicom import WsiDicom
import logging
import numpy as np

logging.getLogger('wsidicom').setLevel(logging.ERROR)

fixed_pids = list(fixed_series.keys())
n = len(fixed_pids)
n_cols = 6
n_rows = (n + n_cols - 1) // n_cols

fig, axes = plt.subplots(n_rows, n_cols, figsize=(n_cols * 3, n_rows * 3))
axes = axes.flat

for ax, pid in zip(axes, fixed_pids):
    sdir = fixed_series[pid]
    try:
        wsi   = WsiDicom.open(sdir)
        w     = wsi.levels.base_level.size.width
        h     = wsi.levels.base_level.size.height
        thumb = wsi.read_thumbnail(size=(300, 300))
        wsi.close()

        thumb_arr    = np.array(thumb)
        tissue_frac  = (thumb_arr.mean(axis=2) < 220).mean()

        ax.imshow(thumb)
        ax.set_title(f'{pid}\n{w}x{h}\ntissue={tissue_frac*100:.0f}%',
                     fontsize=7)
    except Exception as e:
        ax.set_facecolor('#ffcccc')
        ax.text(0.5, 0.5, f'{pid}\nERROR\n{str(e)[:30]}',
                ha='center', va='center',
                transform=ax.transAxes, fontsize=6)
    ax.axis('off')

# Hide unused axes
for ax in axes:
    ax.axis('off')

plt.suptitle(f'Fixed ERROR patients — visual check ({n} slides)', fontsize=12)
plt.tight_layout()
plt.savefig(f'{RESULTS_DIR}/fixed_error_patients_check.png', dpi=100,
            bbox_inches='tight')
plt.show()

# Update census_df with fixed patients and finalize run list #24


if 'status' not in census_df.columns:
    census_df['status'] = 'GOOD'
    census_df.loc[census_df['tissue_frac'].isna(), 'status'] = 'ERROR'

for pid, sdir in fixed_series.items():
    stats_df.loc[stats_df['PatientID'] == pid, 'best_sdir'] = sdir
    # Reclassify fixed patients as WARN (conservative)
    census_df.loc[census_df['PatientID'] == pid, 'status'] = 'WARN'

# Flag the 3 problem slides as WARN not BAD (still real tissue)
problem_slides = ['C3N-03000', 'C3N-03430', 'C3L-04853']
for pid in problem_slides:
    census_df.loc[census_df['PatientID'] == pid, 'status'] = 'WARN'

# Final lists
run_patients  = census_df[census_df['status'].isin(['GOOD','WARN'])]['PatientID'].tolist()
skip_patients = census_df[census_df['status'].isin(['BAD','ERROR'])]['PatientID'].tolist()
# C3N-00198 failed completely — add to skip (guard against duplicate)
if 'C3N-00198' not in skip_patients:
    skip_patients.append('C3N-00198')


# Save
import json
json.dump(run_patients,  open(f'{SCORES_DIR}/patients_to_run.json',  'w'))
json.dump(skip_patients, open(f'{SCORES_DIR}/patients_to_skip.json', 'w'))
census_df.to_csv(f'{SCORES_DIR}/dataset_census_final.csv', index=False)