# -*- coding: utf-8 -*-
"""nci_idc_data_access

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kSboNughDD4R04bhyHOynZDjKzl4uAML
"""

from google.colab import drive #1
drive.mount('/content/drive')

import os #2
DRIVE_BASE  = '/content/drive/MyDrive/cptac_gigatime'
WSI_DIR     = f'{DRIVE_BASE}/wsi_raw'
SCORES_DIR  = f'{DRIVE_BASE}/scores'       # ADD THIS
RESULTS_DIR = f'{DRIVE_BASE}/results'      # ADD THIS

for d in [DRIVE_BASE, WSI_DIR, SCORES_DIR, RESULTS_DIR]:
    os.makedirs(d, exist_ok=True)

# Install all dependencies #3
!pip install idc-index -q --upgrade
!pip install -q wsidicom albumentations huggingface_hub
!apt-get install -y -q openslide-tools libopenjp2-7

"""# Acces data NCI Imaging Data Commons"""

# Connect to IDC and query CPTAC slides #4
from idc_index import IDCClient

client = IDCClient()
print("IDC version:", client.get_idc_version())

query = """
SELECT PatientID, collection_id, StudyInstanceUID,
       SeriesInstanceUID, Modality, series_size_MB
FROM index
WHERE Modality = 'SM'
  AND collection_id IN ('CPTAC', 'cptac_pda')
"""
df = client.sql_query(query)
print(f"Found {len(df)} series, {df['PatientID'].nunique()} patients")

"""# Download slides"""

# Download all patients in batches (crash-safe) #5
import json
from tqdm.notebook import tqdm

WSI_DIR      = f'{DRIVE_BASE}/wsi_raw'
PROGRESS_FILE = f'{DRIVE_BASE}/download_progress.json'
os.makedirs(WSI_DIR, exist_ok=True)

# Load progress (safe to re-run if Colab crashes)
if os.path.exists(PROGRESS_FILE):
    with open(PROGRESS_FILE) as f:
        done = set(json.load(f))
    print(f"Resuming — {len(done)} patients already downloaded")
else:
    done = set()

all_patients = df['PatientID'].unique().tolist()
todo         = [p for p in all_patients if p not in done]
print(f"Remaining: {len(todo)} patients")

for patient_id in tqdm(todo, desc="Patients"):
    try:
        client.download_from_selection(
            patientId=patient_id,
            downloadDir=WSI_DIR,
            show_progress_bar=False   # individual bars get messy in a loop
        )
        done.add(patient_id)

        # Save progress after every patient
        with open(PROGRESS_FILE, 'w') as f:
            json.dump(list(done), f)

    except Exception as e:
        print(f"  Failed {patient_id}: {e}")

print(f"\nDone! {len(done)}/{len(all_patients)} patients downloaded")

# Check folder structure after download #6
import os, glob

WSI_DIR = f'{DRIVE_BASE}/wsi_raw'

# idc-index saves as: wsi_raw/cptac_pda/PatientID/StudyUID/SM_SeriesUID/
dcm_files = glob.glob(f'{WSI_DIR}/**/*.dcm', recursive=True)
patients_on_disk = set(p.split('/')[-4] for p in dcm_files)  # PatientID level

print(f"DICOM files on disk : {len(dcm_files):,}")
print(f"Patients on disk    : {len(patients_on_disk)}")
print(f"\nSample paths:")
for f in dcm_files[:3]:
    print(f"  {f.replace(DRIVE_BASE, '.')}")

# Open one slide and visualize thumbnail #7
from wsidicom import WsiDicom   # <-- import the class directly
from PIL import Image
import matplotlib.pyplot as plt

def find_series_dirs(wsi_dir):
    series_dirs = []
    for root, dirs, files in os.walk(wsi_dir):
        if any(f.endswith('.dcm') for f in files):
            parts = root.replace(wsi_dir+'/', '').split('/')
            patient_id = parts[1] if len(parts) > 1 else 'unknown'
            series_dirs.append((patient_id, root))
    return series_dirs

series_list = find_series_dirs(WSI_DIR)
print(f"Found {len(series_list)} series across {len(set(p for p,_ in series_list))} patients")

# Open first series
patient_id, test_dir = series_list[0]
print(f"\nOpening: {patient_id}")
print(f"Dir: {test_dir}")

wsi = WsiDicom.open(test_dir)   # <-- fixed
print(f"Slide levels : {len(wsi.levels)}")
print(f"Base size    : {wsi.levels.base_level.size}")

# Thumbnail
thumb = wsi.read_thumbnail(size=(512, 512))
plt.figure(figsize=(6, 6))
plt.imshow(thumb)
plt.title(f"Patient: {patient_id}")
plt.axis('off')
plt.tight_layout()
plt.savefig(f'{RESULTS_DIR}/thumb_{patient_id}.png', dpi=100)
plt.show()
wsi.close()

import nbformat

nb = nbformat.read("your_notebook.ipynb", as_version=4)

# Remove problematic widget metadata
if "widgets" in nb.metadata:
    del nb.metadata["widgets"]

nbformat.write(nb, "fixed_notebook.ipynb")